# Generated by Django 5.1.1 on 2026-02-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('credit_score', models.IntegerField()),
                ('geography', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('balance', models.FloatField()),
                ('num_of_products', models.IntegerField()),
                ('has_cr_card', models.IntegerField()),
                ('is_active_member', models.IntegerField()),
                ('churn_risk_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
